// Using Math.random()
var randomNumber = Math.random(); //
console.log(randomNumber);
// If I want a number greater than 0.99 I need to multiply it by 10
console.log(randomNumber * 10)

// Using Math.ceil()
// This method rounds up a decimal number to the nearest integer
var decimalNumber = Math.ceil(Math.random()); // -> In this case the random number generated by Math.random() will be rounded up to the nearest integer
console.log(decimalNumber)

// Use both methods to produce a number 0 - 10 as the answer.
var decimal = Math.random() * 10
var rounded = Math.ceil(decimal)
console.log(rounded)